allowBuilds:
   # vite
   esbuild: true

   # ssh
   ssh2: true

ignoredOptionalDependencies:
   # ssh
   - cpu-features

   # just-bash
   - "@mongodb-js/zstd"
   - "node-liblzma"

minimumReleaseAgeExclude:
   - vite@8.1.0
   - hono@4.12.27
