allowBuilds:
   # vite
   esbuild: true

   # just-bash
   "@mongodb-js/zstd": false
   node-liblzma: false

   # ssh
   ssh2: true

ignoredOptionalDependencies:
	# ssh
   - cpu-features

   # just-bash
   - "@mongodb-js/zstd"
   - "node-liblzma"
